/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Bobashop(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/p109/other/emsbobashop_FINAL.glb')
  const { actions } = useAnimations(animations, group)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="defaultScene">
        <group>
          <mesh
            name="mesh_0"
            castShadow
            receiveShadow
            geometry={nodes.mesh_0.geometry}
            material={nodes.mesh_0.material}
            position={[-1.529, 0.59, -1.84]}
            scale={[1.085, 0.18, 0.524]}
          />
          <mesh
            name="mesh_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh_1.geometry}
            material={nodes.mesh_1.material}
            position={[-1.529, 0.59, -0.72]}
            scale={[1.085, 0.18, 0.524]}
          />
          <mesh
            name="mesh_2"
            castShadow
            receiveShadow
            geometry={nodes.mesh_2.geometry}
            material={nodes.mesh_2.material}
            position={[-1.529, 0.59, 0.4]}
            scale={[1.085, 0.18, 0.524]}
          />
          <mesh
            name="mesh_3"
            castShadow
            receiveShadow
            geometry={nodes.mesh_3.geometry}
            material={nodes.mesh_3.material}
            position={[-1.529, 0.59, 1.52]}
            scale={[1.085, 0.18, 0.524]}
          />
          <mesh
            name="mesh_4"
            castShadow
            receiveShadow
            geometry={nodes.mesh_4.geometry}
            material={nodes.mesh_4.material}
            position={[1.248, 0.59, 2.08]}
            scale={[2.19, 0.18, 0.524]}
          />
          <mesh
            name="mesh_5"
            castShadow
            receiveShadow
            geometry={nodes.mesh_5.geometry}
            material={nodes.mesh_5.material}
            position={[1.802, 0.59, 1.52]}
            scale={[1.085, 0.18, 0.524]}
          />
          <mesh
            name="mesh_6"
            castShadow
            receiveShadow
            geometry={nodes.mesh_6.geometry}
            material={nodes.mesh_6.material}
            position={[1.248, 0.59, 0.96]}
            scale={[2.19, 0.18, 0.524]}
          />
          <mesh
            name="mesh_7"
            castShadow
            receiveShadow
            geometry={nodes.mesh_7.geometry}
            material={nodes.mesh_7.material}
            position={[1.802, 0.59, 0.4]}
            scale={[1.085, 0.18, 0.524]}
          />
          <mesh
            name="mesh_8"
            castShadow
            receiveShadow
            geometry={nodes.mesh_8.geometry}
            material={nodes.mesh_8.material}
            position={[1.248, 0.59, -0.16]}
            scale={[2.19, 0.18, 0.524]}
          />
          <mesh
            name="mesh_9"
            castShadow
            receiveShadow
            geometry={nodes.mesh_9.geometry}
            material={nodes.mesh_9.material}
            position={[1.802, 0.59, -0.72]}
            scale={[1.085, 0.18, 0.524]}
          />
          <mesh
            name="mesh_10"
            castShadow
            receiveShadow
            geometry={nodes.mesh_10.geometry}
            material={nodes.mesh_10.material}
            position={[1.248, 0.59, -1.28]}
            scale={[2.19, 0.18, 0.524]}
          />
          <mesh
            name="mesh_11"
            castShadow
            receiveShadow
            geometry={nodes.mesh_11.geometry}
            material={nodes.mesh_11.material}
            position={[1.802, 0.59, -1.84]}
            scale={[1.085, 0.18, 0.524]}
          />
          <mesh
            name="mesh_12"
            castShadow
            receiveShadow
            geometry={nodes.mesh_12.geometry}
            material={nodes.mesh_12.material}
            position={[-0.975, 0.59, 2.08]}
            scale={[2.19, 0.18, 0.524]}
          />
          <mesh
            name="mesh_13"
            castShadow
            receiveShadow
            geometry={nodes.mesh_13.geometry}
            material={nodes.mesh_13.material}
            position={[0.138, 0.59, 1.52]}
            scale={[2.19, 0.18, 0.524]}
          />
          <mesh
            name="mesh_14"
            castShadow
            receiveShadow
            geometry={nodes.mesh_14.geometry}
            material={nodes.mesh_14.material}
            position={[0.138, 0.59, 0.4]}
            scale={[2.19, 0.18, 0.524]}
          />
          <mesh
            name="mesh_15"
            castShadow
            receiveShadow
            geometry={nodes.mesh_15.geometry}
            material={nodes.mesh_15.material}
            position={[-0.975, 0.59, 0.96]}
            scale={[2.19, 0.18, 0.524]}
          />
          <mesh
            name="mesh_16"
            castShadow
            receiveShadow
            geometry={nodes.mesh_16.geometry}
            material={nodes.mesh_16.material}
            position={[0.138, 0.59, -0.72]}
            scale={[2.19, 0.18, 0.524]}
          />
          <mesh
            name="mesh_17"
            castShadow
            receiveShadow
            geometry={nodes.mesh_17.geometry}
            material={nodes.mesh_17.material}
            position={[-0.975, 0.59, -0.16]}
            scale={[2.19, 0.18, 0.524]}
          />
          <mesh
            name="mesh_18"
            castShadow
            receiveShadow
            geometry={nodes.mesh_18.geometry}
            material={nodes.mesh_18.material}
            position={[0.138, 0.59, -1.84]}
            scale={[2.19, 0.18, 0.524]}
          />
          <mesh
            name="mesh_19"
            castShadow
            receiveShadow
            geometry={nodes.mesh_19.geometry}
            material={nodes.mesh_19.material}
            position={[-0.975, 0.59, -1.28]}
            scale={[2.19, 0.18, 0.524]}
          />
        </group>
        <group>
          <mesh
            name="mesh_20"
            castShadow
            receiveShadow
            geometry={nodes.mesh_20.geometry}
            material={nodes.mesh_20.material}
            position={[1.513, 0.752, -0.53]}
            scale={[1.194, 0.161, 3.237]}
          />
          <mesh
            name="mesh_21"
            castShadow
            receiveShadow
            geometry={nodes.mesh_21.geometry}
            material={nodes.mesh_21.material}
            position={[1.513, 1.739, -0.53]}
            scale={[1.194, 0.161, 3.237]}
          />
          <mesh
            name="mesh_22"
            castShadow
            receiveShadow
            geometry={nodes.mesh_22.geometry}
            material={nodes.mesh_22.material}
            position={[-0.035, 0.689, -1.056]}
            scale={[1.803, 0.046, 2.11]}
          />
          <mesh
            name="mesh_23"
            castShadow
            receiveShadow
            geometry={nodes.mesh_23.geometry}
            material={nodes.mesh_23.material}
            position={[1.694, 1.244, -0.594]}
            scale={[0.755, 0.755, 2.877]}
          />
          <mesh
            name="mesh_24"
            castShadow
            receiveShadow
            geometry={nodes.mesh_24.geometry}
            material={nodes.mesh_24.material}
            position={[1.009, 1.244, -0.594]}
            scale={[-0.051, 0.679, 0.896]}
          />
          <mesh
            name="mesh_25"
            castShadow
            receiveShadow
            geometry={nodes.mesh_25.geometry}
            material={nodes.mesh_25.material}
            position={[1.009, 1.244, 0.37]}
            scale={[-0.051, 0.679, 0.896]}
          />
          <mesh
            name="mesh_26"
            castShadow
            receiveShadow
            geometry={nodes.mesh_26.geometry}
            material={nodes.mesh_26.material}
            position={[1.009, 1.244, -1.56]}
            scale={[-0.051, 0.679, 0.896]}
          />
          <mesh
            name="mesh_27"
            castShadow
            receiveShadow
            geometry={nodes.mesh_27.geometry}
            material={nodes.mesh_27.material}
            position={[0.976, 1.436, 0.37]}
            scale={[-0.055, 0.06, 0.299]}
          />
          <mesh
            name="mesh_28"
            castShadow
            receiveShadow
            geometry={nodes.mesh_28.geometry}
            material={nodes.mesh_28.material}
            position={[0.976, 1.436, -0.594]}
            scale={[-0.055, 0.06, 0.299]}
          />
          <mesh
            name="mesh_29"
            castShadow
            receiveShadow
            geometry={nodes.mesh_29.geometry}
            material={nodes.mesh_29.material}
            position={[0.976, 1.436, -1.56]}
            scale={[-0.055, 0.06, 0.299]}
          />
          <mesh
            name="mesh_30"
            castShadow
            receiveShadow
            geometry={nodes.mesh_30.geometry}
            material={nodes.mesh_30.material}
            position={[1.513, 1.244, 0.859]}
            scale={[0.755, 0.755, 0.314]}
          />
        </group>
        <group>
          <mesh
            name="mesh_31"
            castShadow
            receiveShadow
            geometry={nodes.mesh_31.geometry}
            material={nodes.mesh_31.material}
            position={[-1.537, 1.221, 0.162]}
            scale={[1.138, 1.085, 1.366]}
          />
          <mesh
            name="mesh_32"
            castShadow
            receiveShadow
            geometry={nodes.mesh_32.geometry}
            material={nodes.mesh_32.material}
            position={[-1.382, 1.221, 0.162]}
            scale={[0.952, 0.934, 1.176]}
          />
          <mesh
            name="mesh_33"
            castShadow
            receiveShadow
            geometry={nodes.mesh_33.geometry}
            material={nodes.mesh_33.material}
            position={[-1.368, 1.221, -0.155]}
            scale={[0.992, 0.379, 0.073]}
          />
        </group>
        <mesh
          name="mesh_34"
          castShadow
          receiveShadow
          geometry={nodes.mesh_34.geometry}
          material={nodes.mesh_34.material}
        />
        <group>
          <mesh
            name="mesh_35"
            castShadow
            receiveShadow
            geometry={nodes.mesh_35.geometry}
            material={nodes.mesh_35.material}
            position={[-1.934, 2.031, -1.321]}
            scale={[0.096, 0.722, 0.159]}
          />
          <mesh
            name="mesh_36"
            castShadow
            receiveShadow
            geometry={nodes.mesh_36.geometry}
            material={nodes.mesh_36.material}
            position={[-1.934, 1.737, -1.591]}
            scale={[0.125, 0.167, 0.144]}
          />
          <mesh
            name="mesh_37"
            castShadow
            receiveShadow
            geometry={nodes.mesh_37.geometry}
            material={nodes.mesh_37.material}
            position={[-1.934, 1.737, -1.051]}
            scale={[0.125, 0.167, 0.144]}
          />
          <mesh
            name="mesh_38"
            castShadow
            receiveShadow
            geometry={nodes.mesh_38.geometry}
            material={nodes.mesh_38.material}
            position={[-1.748, 2.321, -1.321]}
            scale={[0.43, 0.068, 0.153]}
          />
        </group>
        <group position={[-0.209, 0, 0]}>
          <mesh
            name="mesh_39"
            castShadow
            receiveShadow
            geometry={nodes.mesh_39.geometry}
            material={nodes.mesh_39.material}
            position={[-1.389, 0.89, 1.629]}
            scale={[0.688, 0.409, 1.319]}
          />
          <mesh
            name="mesh_40"
            castShadow
            receiveShadow
            geometry={nodes.mesh_40.geometry}
            material={nodes.mesh_40.material}
            position={[-1.389, 1.272, 1.629]}
            scale={[0.987, 0.968, 1.366]}
          />
          <mesh
            name="mesh_41"
            castShadow
            receiveShadow
            geometry={nodes.mesh_41.geometry}
            material={nodes.mesh_41.material}
            position={[-1.389, 1.668, 1.109]}
            scale={[0.51, 0.277, 0.034]}
          />
          <mesh
            name="mesh_42"
            castShadow
            receiveShadow
            geometry={nodes.mesh_42.geometry}
            material={nodes.mesh_42.material}
            position={[-1.389, 1.668, 1.32]}
            scale={[0.853, 0.233, 0.592]}
          />
        </group>
        <group position={[0, -0.889, 0]}>
          <mesh
            name="mesh_43"
            castShadow
            receiveShadow
            geometry={nodes.mesh_43.geometry}
            material={nodes.mesh_43.material}
            position={[-1.832, 3.151, 1.629]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[0.867, 0.069, 0.504]}
          />
          <mesh
            name="mesh_44"
            castShadow
            receiveShadow
            geometry={nodes.mesh_44.geometry}
            material={nodes.mesh_44.material}
            position={[-1.83, 3.101, 1.929]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[0.129, 0.088, 0.407]}
          />
          <mesh
            name="mesh_45"
            castShadow
            receiveShadow
            geometry={nodes.mesh_45.geometry}
            material={nodes.mesh_45.material}
            position={[-2.086, 3.425, 1.629]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[1.035, 1.316, 0.063]}
          />
          <mesh
            name="mesh_46"
            castShadow
            receiveShadow
            geometry={nodes.mesh_46.geometry}
            material={nodes.mesh_46.material}
            position={[-1.83, 3.655, 1.929]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[0.129, 0.088, 0.407]}
          />
          <mesh
            name="mesh_47"
            castShadow
            receiveShadow
            geometry={nodes.mesh_47.geometry}
            material={nodes.mesh_47.material}
            position={[-1.832, 3.705, 1.629]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[0.867, 0.069, 0.504]}
          />
          <mesh
            name="mesh_48"
            castShadow
            receiveShadow
            geometry={nodes.mesh_48.geometry}
            material={nodes.mesh_48.material}
            position={[-1.83, 3.655, 1.329]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[0.129, 0.088, 0.407]}
          />
          <mesh
            name="mesh_49"
            castShadow
            receiveShadow
            geometry={nodes.mesh_49.geometry}
            material={nodes.mesh_49.material}
            position={[-1.83, 3.101, 1.329]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[0.129, 0.088, 0.407]}
          />
        </group>
        <group>
          <mesh
            name="mesh_50"
            castShadow
            receiveShadow
            geometry={nodes.mesh_50.geometry}
            material={nodes.mesh_50.material}
            position={[-1.736, 3.955, -0.632]}
            scale={[0.511, 0.781, 2.186]}
          />
          <mesh
            name="mesh_51"
            castShadow
            receiveShadow
            geometry={nodes.mesh_51.geometry}
            material={nodes.mesh_51.material}
            position={[-1.788, 3.955, -0.632]}
            scale={[0.572, 0.874, 2.447]}
          />
        </group>
        <group position={[0, -0.02, 0.177]} rotation={[0, -0.169, 0]}>
          <mesh
            name="mesh_52"
            castShadow
            receiveShadow
            geometry={nodes.mesh_52.geometry}
            material={nodes.mesh_52.material}
            position={[-1.634, 1.86, -0.061]}
            scale={[0.402, 0.149, 0.402]}
          />
          <mesh
            name="mesh_53"
            castShadow
            receiveShadow
            geometry={nodes.mesh_53.geometry}
            material={nodes.mesh_53.material}
            position={[-1.634, 1.825, -0.061]}
            scale={[0.382, 0.142, 0.382]}
          />
          <mesh
            name="mesh_54"
            castShadow
            receiveShadow
            geometry={nodes.mesh_54.geometry}
            material={nodes.mesh_54.material}
            position={[-1.634, 1.966, -0.061]}
            scale={[0.323, 0.081, 0.33]}
          />
          <mesh
            name="mesh_55"
            castShadow
            receiveShadow
            geometry={nodes.mesh_55.geometry}
            material={nodes.mesh_55.material}
            position={[-1.634, 2.032, -0.061]}
            scale={[0.189, 0.047, 0.193]}
          />
          <mesh
            name="mesh_56"
            castShadow
            receiveShadow
            geometry={nodes.mesh_56.geometry}
            material={nodes.mesh_56.material}
            position={[-1.634, 2.314, -0.061]}
            scale={[0.256, 0.52, 0.262]}
          />
          <mesh
            name="mesh_57"
            castShadow
            receiveShadow
            geometry={nodes.mesh_57.geometry}
            material={nodes.mesh_57.material}
            position={[-1.634, 2.233, 0.109]}
            scale={[0.069, 0.057, 0.092]}
          />
          <mesh
            name="mesh_58"
            castShadow
            receiveShadow
            geometry={nodes.mesh_58.geometry}
            material={nodes.mesh_58.material}
            position={[-1.634, 2.34, 0.153]}
            scale={[0.069, 0.271, 0.049]}
          />
          <mesh
            name="mesh_59"
            castShadow
            receiveShadow
            geometry={nodes.mesh_59.geometry}
            material={nodes.mesh_59.material}
            position={[-1.634, 2.448, 0.109]}
            scale={[0.069, 0.057, 0.08]}
          />
          <mesh
            name="mesh_60"
            castShadow
            receiveShadow
            geometry={nodes.mesh_60.geometry}
            material={nodes.mesh_60.material}
            position={[-1.634, 2.603, -0.061]}
            scale={[0.366, 0.092, 0.374]}
          />
          <mesh
            name="mesh_61"
            castShadow
            receiveShadow
            geometry={nodes.mesh_61.geometry}
            material={nodes.mesh_61.material}
            position={[-1.634, 2.651, -0.061]}
            scale={[0.106, 0.026, 0.108]}
          />
        </group>
        <group position={[0, 0, 0.039]} rotation={[0, 0.24, 0]}>
          <mesh
            name="mesh_62"
            castShadow
            receiveShadow
            geometry={nodes.mesh_62.geometry}
            material={nodes.mesh_62.material}
            position={[-1.634, 1.86, -0.061]}
            scale={[0.402, 0.149, 0.402]}
          />
          <mesh
            name="mesh_63"
            castShadow
            receiveShadow
            geometry={nodes.mesh_63.geometry}
            material={nodes.mesh_63.material}
            position={[-1.634, 1.825, -0.061]}
            scale={[0.382, 0.142, 0.382]}
          />
          <mesh
            name="mesh_64"
            castShadow
            receiveShadow
            geometry={nodes.mesh_64.geometry}
            material={nodes.mesh_64.material}
            position={[-1.634, 1.966, -0.061]}
            scale={[0.323, 0.081, 0.33]}
          />
          <mesh
            name="mesh_65"
            castShadow
            receiveShadow
            geometry={nodes.mesh_65.geometry}
            material={nodes.mesh_65.material}
            position={[-1.634, 2.032, -0.061]}
            scale={[0.189, 0.047, 0.193]}
          />
          <mesh
            name="mesh_66"
            castShadow
            receiveShadow
            geometry={nodes.mesh_66.geometry}
            material={nodes.mesh_66.material}
            position={[-1.634, 2.314, -0.061]}
            scale={[0.256, 0.52, 0.262]}
          />
          <mesh
            name="mesh_67"
            castShadow
            receiveShadow
            geometry={nodes.mesh_67.geometry}
            material={nodes.mesh_67.material}
            position={[-1.634, 2.233, 0.109]}
            scale={[0.069, 0.057, 0.092]}
          />
          <mesh
            name="mesh_68"
            castShadow
            receiveShadow
            geometry={nodes.mesh_68.geometry}
            material={nodes.mesh_68.material}
            position={[-1.634, 2.34, 0.153]}
            scale={[0.069, 0.271, 0.049]}
          />
          <mesh
            name="mesh_69"
            castShadow
            receiveShadow
            geometry={nodes.mesh_69.geometry}
            material={nodes.mesh_69.material}
            position={[-1.634, 2.448, 0.109]}
            scale={[0.069, 0.057, 0.08]}
          />
          <mesh
            name="mesh_70"
            castShadow
            receiveShadow
            geometry={nodes.mesh_70.geometry}
            material={nodes.mesh_70.material}
            position={[-1.634, 2.592, -0.061]}
            scale={[0.33, 0.083, 0.337]}
          />
          <mesh
            name="mesh_71"
            castShadow
            receiveShadow
            geometry={nodes.mesh_71.geometry}
            material={nodes.mesh_71.material}
            position={[-1.634, 2.638, -0.061]}
            scale={[0.106, 0.026, 0.108]}
          />
        </group>
        <group position={[-0.37, 0, 0.014]}>
          <mesh
            name="mesh_72"
            castShadow
            receiveShadow
            geometry={nodes.mesh_72.geometry}
            material={nodes.mesh_72.material}
            position={[1.82, 2.227, -1.811]}
            scale={[0.436, 0.923, 0.436]}
          />
          <mesh
            name="mesh_73"
            castShadow
            receiveShadow
            geometry={nodes.mesh_73.geometry}
            material={nodes.mesh_73.material}
            position={[1.82, 1.868, -1.811]}
            scale={[0.461, 0.098, 0.461]}
          />
          <mesh
            name="mesh_74"
            castShadow
            receiveShadow
            geometry={nodes.mesh_74.geometry}
            material={nodes.mesh_74.material}
            position={[1.855, 2.625, -1.811]}
            scale={[0.554, 0.098, 0.461]}
          />
          <mesh
            name="mesh_75"
            castShadow
            receiveShadow
            geometry={nodes.mesh_75.geometry}
            material={nodes.mesh_75.material}
            position={[2.087, 2.531, -1.811]}
            scale={[0.086, 0.138, 0.101]}
          />
          <mesh
            name="mesh_76"
            castShadow
            receiveShadow
            geometry={nodes.mesh_76.geometry}
            material={nodes.mesh_76.material}
            position={[2.025, 2.731, -1.811]}
            rotation={[-Math.PI / 4, 0, Math.PI / 2]}
            scale={0.088}
          />
          <mesh
            name="mesh_77"
            castShadow
            receiveShadow
            geometry={nodes.mesh_77.geometry}
            material={nodes.mesh_77.material}
            position={[1.678, 2.731, -1.811]}
            rotation={[-Math.PI / 4, 0, Math.PI / 2]}
            scale={0.088}
          />
          <mesh
            name="mesh_78"
            castShadow
            receiveShadow
            geometry={nodes.mesh_78.geometry}
            material={nodes.mesh_78.material}
            position={[2.26, 1.848, -1.811]}
            scale={[0.302, 0.064, 0.302]}
          />
        </group>
        <group position={[-0.37, 0, 0.498]}>
          <mesh
            name="mesh_79"
            castShadow
            receiveShadow
            geometry={nodes.mesh_79.geometry}
            material={nodes.mesh_79.material}
            position={[1.82, 2.227, -1.811]}
            scale={[0.436, 0.923, 0.436]}
          />
          <mesh
            name="mesh_80"
            castShadow
            receiveShadow
            geometry={nodes.mesh_80.geometry}
            material={nodes.mesh_80.material}
            position={[1.82, 1.868, -1.811]}
            scale={[0.461, 0.098, 0.461]}
          />
          <mesh
            name="mesh_81"
            castShadow
            receiveShadow
            geometry={nodes.mesh_81.geometry}
            material={nodes.mesh_81.material}
            position={[1.855, 2.625, -1.811]}
            scale={[0.554, 0.098, 0.461]}
          />
          <mesh
            name="mesh_82"
            castShadow
            receiveShadow
            geometry={nodes.mesh_82.geometry}
            material={nodes.mesh_82.material}
            position={[2.087, 2.531, -1.811]}
            scale={[0.086, 0.138, 0.101]}
          />
          <mesh
            name="mesh_83"
            castShadow
            receiveShadow
            geometry={nodes.mesh_83.geometry}
            material={nodes.mesh_83.material}
            position={[2.025, 2.731, -1.811]}
            rotation={[-Math.PI / 4, 0, Math.PI / 2]}
            scale={0.088}
          />
          <mesh
            name="mesh_84"
            castShadow
            receiveShadow
            geometry={nodes.mesh_84.geometry}
            material={nodes.mesh_84.material}
            position={[1.678, 2.731, -1.811]}
            rotation={[-Math.PI / 4, 0, Math.PI / 2]}
            scale={0.088}
          />
          <mesh
            name="mesh_85"
            castShadow
            receiveShadow
            geometry={nodes.mesh_85.geometry}
            material={nodes.mesh_85.material}
            position={[2.26, 1.848, -1.811]}
            scale={[0.302, 0.064, 0.302]}
          />
        </group>
        <group>
          <mesh
            name="mesh_86"
            castShadow
            receiveShadow
            geometry={nodes.mesh_86.geometry}
            material={nodes.mesh_86.material}
          />
          <mesh
            name="mesh_87"
            castShadow
            receiveShadow
            geometry={nodes.mesh_87.geometry}
            material={nodes.mesh_87.material}
          />
        </group>
        <group>
          <mesh
            name="mesh_88"
            castShadow
            receiveShadow
            geometry={nodes.mesh_88.geometry}
            material={nodes.mesh_88.material}
            position={[0, 5, -2.25]}
            scale={[5, 0.325, 0.4]}
          />
          <mesh
            name="mesh_89"
            castShadow
            receiveShadow
            geometry={nodes.mesh_89.geometry}
            material={nodes.mesh_89.material}
            position={[-2.25, 5, 0]}
            scale={[0.4, 0.325, 5]}
          />
          <mesh
            name="mesh_90"
            castShadow
            receiveShadow
            geometry={nodes.mesh_90.geometry}
            material={nodes.mesh_90.material}
            position={[0, 5.204, -2.25]}
            scale={[5.274, 0.343, 0.422]}
          />
          <mesh
            name="mesh_91"
            castShadow
            receiveShadow
            geometry={nodes.mesh_91.geometry}
            material={nodes.mesh_91.material}
            position={[-2.25, 5.204, 0]}
            scale={[0.422, 0.343, 5.274]}
          />
        </group>
        <group>
          <mesh
            name="mesh_92"
            castShadow
            receiveShadow
            geometry={nodes.mesh_92.geometry}
            material={nodes.mesh_92.material}
            position={[0.73, 3.324, -2.221]}
            scale={[2.1, 0.142, 0.082]}
          />
          <mesh
            name="mesh_93"
            castShadow
            receiveShadow
            geometry={nodes.mesh_93.geometry}
            material={nodes.mesh_93.material}
            position={[0.73, 2.396, -2.221]}
            scale={[2.1, 0.142, 0.082]}
          />
          <mesh
            name="mesh_94"
            castShadow
            receiveShadow
            geometry={nodes.mesh_94.geometry}
            material={nodes.mesh_94.material}
            position={[-0.249, 2.845, -2.221]}
            scale={[0.142, 0.838, 0.082]}
          />
          <mesh
            name="mesh_95"
            castShadow
            receiveShadow
            geometry={nodes.mesh_95.geometry}
            material={nodes.mesh_95.material}
            position={[1.708, 2.845, -2.221]}
            scale={[0.142, 0.838, 0.082]}
          />
          <mesh
            name="mesh_96"
            castShadow
            receiveShadow
            geometry={nodes.mesh_96.geometry}
            material={nodes.mesh_96.material}
            position={[0.73, 3.324, -2.327]}
            scale={[2.1, 0.142, 0.082]}
          />
          <mesh
            name="mesh_97"
            castShadow
            receiveShadow
            geometry={nodes.mesh_97.geometry}
            material={nodes.mesh_97.material}
            position={[1.708, 3.773, -2.327]}
            scale={[0.142, 0.838, 0.082]}
          />
          <mesh
            name="mesh_98"
            castShadow
            receiveShadow
            geometry={nodes.mesh_98.geometry}
            material={nodes.mesh_98.material}
            position={[0.73, 4.252, -2.327]}
            scale={[2.1, 0.142, 0.082]}
          />
          <mesh
            name="mesh_99"
            castShadow
            receiveShadow
            geometry={nodes.mesh_99.geometry}
            material={nodes.mesh_99.material}
            position={[-0.249, 3.773, -2.327]}
            scale={[0.142, 0.838, 0.082]}
          />
          <mesh
            name="mesh_100"
            castShadow
            receiveShadow
            geometry={nodes.mesh_100.geometry}
            material={nodes.mesh_100.material}
            position={[0.73, 3.368, -2.221]}
            scale={[0.277, 0.175, 0.045]}
          />
        </group>
        <mesh
          name="mesh_101"
          castShadow
          receiveShadow
          geometry={nodes.mesh_101.geometry}
          material={nodes.mesh_101.material}
          position={[1.487, 1.837, -0.809]}
          scale={[0.694, 0.034, 0.445]}
        />
        <group>
          <mesh
            name="mesh_102"
            castShadow
            receiveShadow
            geometry={nodes.mesh_102.geometry}
            material={nodes.mesh_102.material}
            position={[1.284, 1.959, -0.91]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_103"
            castShadow
            receiveShadow
            geometry={nodes.mesh_103.geometry}
            material={nodes.mesh_103.material}
            position={[1.284, 2.009, -0.91]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_104"
            castShadow
            receiveShadow
            geometry={nodes.mesh_104.geometry}
            material={nodes.mesh_104.material}
            position={[1.284, 2.059, -0.91]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_105"
            castShadow
            receiveShadow
            geometry={nodes.mesh_105.geometry}
            material={nodes.mesh_105.material}
            position={[1.284, 2.109, -0.91]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_106"
            castShadow
            receiveShadow
            geometry={nodes.mesh_106.geometry}
            material={nodes.mesh_106.material}
            position={[1.284, 2.159, -0.91]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_107"
            castShadow
            receiveShadow
            geometry={nodes.mesh_107.geometry}
            material={nodes.mesh_107.material}
            position={[1.48, 2.159, -0.91]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_108"
            castShadow
            receiveShadow
            geometry={nodes.mesh_108.geometry}
            material={nodes.mesh_108.material}
            position={[1.48, 2.109, -0.91]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_109"
            castShadow
            receiveShadow
            geometry={nodes.mesh_109.geometry}
            material={nodes.mesh_109.material}
            position={[1.48, 2.059, -0.91]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_110"
            castShadow
            receiveShadow
            geometry={nodes.mesh_110.geometry}
            material={nodes.mesh_110.material}
            position={[1.48, 2.009, -0.91]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_111"
            castShadow
            receiveShadow
            geometry={nodes.mesh_111.geometry}
            material={nodes.mesh_111.material}
            position={[1.48, 1.959, -0.91]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_112"
            castShadow
            receiveShadow
            geometry={nodes.mesh_112.geometry}
            material={nodes.mesh_112.material}
            position={[1.284, 1.959, -0.72]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_113"
            castShadow
            receiveShadow
            geometry={nodes.mesh_113.geometry}
            material={nodes.mesh_113.material}
            position={[1.284, 2.009, -0.72]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_114"
            castShadow
            receiveShadow
            geometry={nodes.mesh_114.geometry}
            material={nodes.mesh_114.material}
            position={[1.284, 2.059, -0.72]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_115"
            castShadow
            receiveShadow
            geometry={nodes.mesh_115.geometry}
            material={nodes.mesh_115.material}
            position={[1.284, 2.109, -0.72]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_116"
            castShadow
            receiveShadow
            geometry={nodes.mesh_116.geometry}
            material={nodes.mesh_116.material}
            position={[1.284, 2.159, -0.72]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_117"
            castShadow
            receiveShadow
            geometry={nodes.mesh_117.geometry}
            material={nodes.mesh_117.material}
            position={[1.48, 2.159, -0.72]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_118"
            castShadow
            receiveShadow
            geometry={nodes.mesh_118.geometry}
            material={nodes.mesh_118.material}
            position={[1.48, 2.109, -0.72]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_119"
            castShadow
            receiveShadow
            geometry={nodes.mesh_119.geometry}
            material={nodes.mesh_119.material}
            position={[1.48, 2.059, -0.72]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_120"
            castShadow
            receiveShadow
            geometry={nodes.mesh_120.geometry}
            material={nodes.mesh_120.material}
            position={[1.48, 2.009, -0.72]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_121"
            castShadow
            receiveShadow
            geometry={nodes.mesh_121.geometry}
            material={nodes.mesh_121.material}
            position={[1.48, 1.959, -0.72]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_122"
            castShadow
            receiveShadow
            geometry={nodes.mesh_122.geometry}
            material={nodes.mesh_122.material}
            position={[1.679, 1.959, -0.91]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_123"
            castShadow
            receiveShadow
            geometry={nodes.mesh_123.geometry}
            material={nodes.mesh_123.material}
            position={[1.679, 1.959, -0.72]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_124"
            castShadow
            receiveShadow
            geometry={nodes.mesh_124.geometry}
            material={nodes.mesh_124.material}
            position={[1.679, 2.009, -0.72]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_125"
            castShadow
            receiveShadow
            geometry={nodes.mesh_125.geometry}
            material={nodes.mesh_125.material}
            position={[1.679, 2.059, -0.72]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_126"
            castShadow
            receiveShadow
            geometry={nodes.mesh_126.geometry}
            material={nodes.mesh_126.material}
            position={[1.679, 2.009, -0.91]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_127"
            castShadow
            receiveShadow
            geometry={nodes.mesh_127.geometry}
            material={nodes.mesh_127.material}
            position={[1.679, 2.059, -0.91]}
            scale={[0.086, -0.111, 0.086]}
          />
          <mesh
            name="mesh_128"
            castShadow
            receiveShadow
            geometry={nodes.mesh_128.geometry}
            material={nodes.mesh_128.material}
            position={[1.786, 1.924, 0.81]}
            scale={[0.086, 0.111, 0.086]}
          />
        </group>
        <group position={[0.981, 1.273, -0.272]} scale={0.329}>
          <mesh
            name="mesh_129"
            castShadow
            receiveShadow
            geometry={nodes.mesh_129.geometry}
            material={nodes.mesh_129.material}
            position={[1.571, 1.855, -0.53]}
            scale={0.299}
          />
          <mesh
            name="mesh_130"
            castShadow
            receiveShadow
            geometry={nodes.mesh_130.geometry}
            material={nodes.mesh_130.material}
            position={[1.571, 1.855, 0.53]}
            scale={0.299}
          />
          <mesh
            name="mesh_131"
            castShadow
            receiveShadow
            geometry={nodes.mesh_131.geometry}
            material={nodes.mesh_131.material}
            position={[1.096, 2.441, 0]}
            scale={[0.654, 0.777, 0.735]}
          />
          <mesh
            name="mesh_132"
            castShadow
            receiveShadow
            geometry={nodes.mesh_132.geometry}
            material={nodes.mesh_132.material}
            position={[1.096, 3.183, -0.422]}
            rotation={[-0.39, 0, 0]}
            scale={[0.19, 0.665, 0.19]}
          />
          <mesh
            name="mesh_133"
            castShadow
            receiveShadow
            geometry={nodes.mesh_133.geometry}
            material={nodes.mesh_133.material}
            position={[1.096, 3.163, 0]}
            scale={[0.685, 0.125, 0.77]}
          />
        </group>
        <group position={[1.464, 1.454, -0.496]} rotation={[0, -0.344, 0]} scale={0.221}>
          <mesh
            name="mesh_134"
            castShadow
            receiveShadow
            geometry={nodes.mesh_134.geometry}
            material={nodes.mesh_134.material}
            position={[1.571, 1.855, -0.53]}
            scale={0.299}
          />
          <mesh
            name="mesh_135"
            castShadow
            receiveShadow
            geometry={nodes.mesh_135.geometry}
            material={nodes.mesh_135.material}
            position={[1.571, 1.855, 0.53]}
            scale={0.299}
          />
          <mesh
            name="mesh_136"
            castShadow
            receiveShadow
            geometry={nodes.mesh_136.geometry}
            material={nodes.mesh_136.material}
            position={[1.096, 2.441, 0]}
            scale={[0.654, 0.777, 0.735]}
          />
          <mesh
            name="mesh_137"
            castShadow
            receiveShadow
            geometry={nodes.mesh_137.geometry}
            material={nodes.mesh_137.material}
            position={[1.096, 3.183, -0.422]}
            rotation={[-0.39, 0, 0]}
            scale={[0.19, 0.665, 0.19]}
          />
          <mesh
            name="mesh_138"
            castShadow
            receiveShadow
            geometry={nodes.mesh_138.geometry}
            material={nodes.mesh_138.material}
            position={[1.096, 3.163, 0]}
            scale={[0.685, 0.125, 0.77]}
          />
        </group>
        <group position={[1.613, 1.553, -0.081]} rotation={[0, 0.193, 0]} scale={0.161}>
          <mesh
            name="mesh_139"
            castShadow
            receiveShadow
            geometry={nodes.mesh_139.geometry}
            material={nodes.mesh_139.material}
            position={[1.571, 1.855, -0.53]}
            scale={0.299}
          />
          <mesh
            name="mesh_140"
            castShadow
            receiveShadow
            geometry={nodes.mesh_140.geometry}
            material={nodes.mesh_140.material}
            position={[1.571, 1.855, 0.53]}
            scale={0.299}
          />
          <mesh
            name="mesh_141"
            castShadow
            receiveShadow
            geometry={nodes.mesh_141.geometry}
            material={nodes.mesh_141.material}
            position={[1.096, 2.441, 0]}
            scale={[0.654, 0.777, 0.735]}
          />
          <mesh
            name="mesh_142"
            castShadow
            receiveShadow
            geometry={nodes.mesh_142.geometry}
            material={nodes.mesh_142.material}
            position={[1.096, 3.183, -0.422]}
            rotation={[-0.39, 0, 0]}
            scale={[0.19, 0.665, 0.19]}
          />
          <mesh
            name="mesh_143"
            castShadow
            receiveShadow
            geometry={nodes.mesh_143.geometry}
            material={nodes.mesh_143.material}
            position={[1.096, 3.163, 0]}
            scale={[0.685, 0.125, 0.77]}
          />
        </group>
        <group position={[-1.775, 2.385, -1.811]} rotation={[0, -0.312, 0]} scale={0.43}>
          <mesh
            name="mesh_144"
            castShadow
            receiveShadow
            geometry={nodes.mesh_144.geometry}
            material={nodes.mesh_144.material}
            position={[1.571, 1.855, -0.53]}
            scale={0.299}
          />
          <mesh
            name="mesh_145"
            castShadow
            receiveShadow
            geometry={nodes.mesh_145.geometry}
            material={nodes.mesh_145.material}
            position={[1.571, 1.855, 0.53]}
            scale={0.299}
          />
          <mesh
            name="mesh_146"
            castShadow
            receiveShadow
            geometry={nodes.mesh_146.geometry}
            material={nodes.mesh_146.material}
            position={[1.096, 2.441, 0]}
            scale={[0.654, 0.777, 0.735]}
          />
          <mesh
            name="mesh_147"
            castShadow
            receiveShadow
            geometry={nodes.mesh_147.geometry}
            material={nodes.mesh_147.material}
            position={[1.096, 3.183, -0.422]}
            rotation={[-0.39, 0, 0]}
            scale={[0.19, 0.665, 0.19]}
          />
          <mesh
            name="mesh_148"
            castShadow
            receiveShadow
            geometry={nodes.mesh_148.geometry}
            material={nodes.mesh_148.material}
            position={[1.096, 3.163, 0]}
            scale={[0.685, 0.125, 0.77]}
          />
        </group>
        <group />
        <group>
          <mesh
            name="mesh_149"
            castShadow
            receiveShadow
            geometry={nodes.mesh_149.geometry}
            material={nodes.mesh_149.material}
            position={[-1.255, 1.89, 0.438]}
            scale={[0.091, 0.134, 0.091]}
          />
          <mesh
            name="mesh_150"
            castShadow
            receiveShadow
            geometry={nodes.mesh_150.geometry}
            material={nodes.mesh_150.material}
            position={[-1.148, 2.096, 0.602]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_151"
            castShadow
            receiveShadow
            geometry={nodes.mesh_151.geometry}
            material={nodes.mesh_151.material}
            position={[-1.148, 2.046, 0.602]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_152"
            castShadow
            receiveShadow
            geometry={nodes.mesh_152.geometry}
            material={nodes.mesh_152.material}
            position={[-1.148, 1.996, 0.602]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_153"
            castShadow
            receiveShadow
            geometry={nodes.mesh_153.geometry}
            material={nodes.mesh_153.material}
            position={[-1.148, 1.946, 0.602]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_154"
            castShadow
            receiveShadow
            geometry={nodes.mesh_154.geometry}
            material={nodes.mesh_154.material}
            position={[-1.148, 1.896, 0.602]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_155"
            castShadow
            receiveShadow
            geometry={nodes.mesh_155.geometry}
            material={nodes.mesh_155.material}
            position={[-1.346, 2.246, 0.643]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_156"
            castShadow
            receiveShadow
            geometry={nodes.mesh_156.geometry}
            material={nodes.mesh_156.material}
            position={[-1.346, 2.196, 0.643]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_157"
            castShadow
            receiveShadow
            geometry={nodes.mesh_157.geometry}
            material={nodes.mesh_157.material}
            position={[-1.346, 2.146, 0.643]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_158"
            castShadow
            receiveShadow
            geometry={nodes.mesh_158.geometry}
            material={nodes.mesh_158.material}
            position={[-1.346, 1.896, 0.643]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_159"
            castShadow
            receiveShadow
            geometry={nodes.mesh_159.geometry}
            material={nodes.mesh_159.material}
            position={[-1.346, 1.946, 0.643]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_160"
            castShadow
            receiveShadow
            geometry={nodes.mesh_160.geometry}
            material={nodes.mesh_160.material}
            position={[-1.346, 2.046, 0.643]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_161"
            castShadow
            receiveShadow
            geometry={nodes.mesh_161.geometry}
            material={nodes.mesh_161.material}
            position={[-1.346, 1.996, 0.643]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_162"
            castShadow
            receiveShadow
            geometry={nodes.mesh_162.geometry}
            material={nodes.mesh_162.material}
            position={[-1.346, 2.096, 0.643]}
            scale={[0.091, -0.134, 0.091]}
          />
        </group>
        <mesh
          name="mesh_163"
          castShadow
          receiveShadow
          geometry={nodes.mesh_163.geometry}
          material={nodes.mesh_163.material}
          position={[1.332, 2.12, 0.393]}
          rotation={[0, 0, 0.741]}
          scale={[0.255, 0.006, 0.307]}
        />
        <group position={[0, 0, -0.28]}>
          <mesh
            name="mesh_164"
            castShadow
            receiveShadow
            geometry={nodes.mesh_164.geometry}
            material={nodes.mesh_164.material}
            position={[0, -0.25, -0.419]}
          />
          <mesh
            name="mesh_165"
            castShadow
            receiveShadow
            geometry={nodes.mesh_165.geometry}
            material={nodes.mesh_165.material}
            position={[0, -0.21, -0.419]}
          />
          <mesh
            name="mesh_166"
            castShadow
            receiveShadow
            geometry={nodes.mesh_166.geometry}
            material={nodes.mesh_166.material}
            position={[0, -0.17, -0.419]}
          />
          <mesh
            name="mesh_167"
            castShadow
            receiveShadow
            geometry={nodes.mesh_167.geometry}
            material={nodes.mesh_167.material}
            position={[0, -0.13, -0.419]}
          />
          <mesh
            name="mesh_168"
            castShadow
            receiveShadow
            geometry={nodes.mesh_168.geometry}
            material={nodes.mesh_168.material}
            position={[0, -0.09, -0.419]}
          />
          <mesh
            name="mesh_169"
            castShadow
            receiveShadow
            geometry={nodes.mesh_169.geometry}
            material={nodes.mesh_169.material}
            position={[-0.061, -0.21, -0.219]}
          />
          <mesh
            name="mesh_170"
            castShadow
            receiveShadow
            geometry={nodes.mesh_170.geometry}
            material={nodes.mesh_170.material}
            position={[-0.061, -0.25, -0.219]}
          />
        </group>
        <group position={[0, -0.586, 0]}>
          <mesh
            name="mesh_171"
            castShadow
            receiveShadow
            geometry={nodes.mesh_171.geometry}
            material={nodes.mesh_171.material}
            position={[-1.817, 3.163, 1.363]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_172"
            castShadow
            receiveShadow
            geometry={nodes.mesh_172.geometry}
            material={nodes.mesh_172.material}
            position={[-1.817, 3.113, 1.363]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_173"
            castShadow
            receiveShadow
            geometry={nodes.mesh_173.geometry}
            material={nodes.mesh_173.material}
            position={[-1.817, 3.063, 1.363]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_174"
            castShadow
            receiveShadow
            geometry={nodes.mesh_174.geometry}
            material={nodes.mesh_174.material}
            position={[-1.817, 3.013, 1.363]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_175"
            castShadow
            receiveShadow
            geometry={nodes.mesh_175.geometry}
            material={nodes.mesh_175.material}
            position={[-1.817, 3.113, 1.561]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_176"
            castShadow
            receiveShadow
            geometry={nodes.mesh_176.geometry}
            material={nodes.mesh_176.material}
            position={[-1.817, 3.063, 1.561]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_177"
            castShadow
            receiveShadow
            geometry={nodes.mesh_177.geometry}
            material={nodes.mesh_177.material}
            position={[-1.817, 3.013, 1.561]}
            scale={[0.091, -0.134, 0.091]}
          />
          <mesh
            name="mesh_178"
            castShadow
            receiveShadow
            geometry={nodes.mesh_178.geometry}
            material={nodes.mesh_178.material}
            position={[-0.631, 0.868, 1.329]}
          />
          <mesh
            name="mesh_179"
            castShadow
            receiveShadow
            geometry={nodes.mesh_179.geometry}
            material={nodes.mesh_179.material}
            position={[-0.631, 0.908, 1.329]}
          />
          <mesh
            name="mesh_180"
            castShadow
            receiveShadow
            geometry={nodes.mesh_180.geometry}
            material={nodes.mesh_180.material}
            position={[-0.631, 0.948, 1.329]}
          />
          <mesh
            name="mesh_181"
            castShadow
            receiveShadow
            geometry={nodes.mesh_181.geometry}
            material={nodes.mesh_181.material}
            position={[-0.631, 0.988, 1.329]}
          />
        </group>
        <group position={[-0.187, 0, 0]}>
          <mesh
            name="mesh_182"
            castShadow
            receiveShadow
            geometry={nodes.mesh_182.geometry}
            material={nodes.mesh_182.material}
            position={[-1.644, 1.963, 2.097]}
            scale={[0.135, -0.055, 0.135]}
          />
          <mesh
            name="mesh_183"
            castShadow
            receiveShadow
            geometry={nodes.mesh_183.geometry}
            material={nodes.mesh_183.material}
            position={[-1.644, 1.913, 2.097]}
            scale={[0.135, -0.055, 0.135]}
          />
          <mesh
            name="mesh_184"
            castShadow
            receiveShadow
            geometry={nodes.mesh_184.geometry}
            material={nodes.mesh_184.material}
            position={[-1.644, 1.863, 2.097]}
            scale={[0.135, -0.055, 0.135]}
          />
          <mesh
            name="mesh_185"
            castShadow
            receiveShadow
            geometry={nodes.mesh_185.geometry}
            material={nodes.mesh_185.material}
            position={[-1.644, 1.813, 2.097]}
            scale={[0.135, -0.055, 0.135]}
          />
          <mesh
            name="mesh_186"
            castShadow
            receiveShadow
            geometry={nodes.mesh_186.geometry}
            material={nodes.mesh_186.material}
            position={[-1.644, 1.963, 1.8]}
            scale={[0.135, -0.055, 0.135]}
          />
          <mesh
            name="mesh_187"
            castShadow
            receiveShadow
            geometry={nodes.mesh_187.geometry}
            material={nodes.mesh_187.material}
            position={[-1.644, 1.913, 1.8]}
            scale={[0.135, -0.055, 0.135]}
          />
          <mesh
            name="mesh_188"
            castShadow
            receiveShadow
            geometry={nodes.mesh_188.geometry}
            material={nodes.mesh_188.material}
            position={[-1.644, 1.863, 1.8]}
            scale={[0.135, -0.055, 0.135]}
          />
          <mesh
            name="mesh_189"
            castShadow
            receiveShadow
            geometry={nodes.mesh_189.geometry}
            material={nodes.mesh_189.material}
            position={[-1.644, 1.813, 1.8]}
            scale={[0.135, -0.055, 0.135]}
          />
        </group>
        <group position={[-1.83, 2.491, -1.16]} rotation={[0, -0.312, 0]} scale={0.365}>
          <mesh
            name="mesh_190"
            castShadow
            receiveShadow
            geometry={nodes.mesh_190.geometry}
            material={nodes.mesh_190.material}
            position={[1.571, 1.855, -0.53]}
            scale={0.299}
          />
          <mesh
            name="mesh_191"
            castShadow
            receiveShadow
            geometry={nodes.mesh_191.geometry}
            material={nodes.mesh_191.material}
            position={[1.571, 1.855, 0.53]}
            scale={0.299}
          />
          <mesh
            name="mesh_192"
            castShadow
            receiveShadow
            geometry={nodes.mesh_192.geometry}
            material={nodes.mesh_192.material}
            position={[1.096, 2.441, 0]}
            scale={[0.654, 0.777, 0.735]}
          />
          <mesh
            name="mesh_193"
            castShadow
            receiveShadow
            geometry={nodes.mesh_193.geometry}
            material={nodes.mesh_193.material}
            position={[1.096, 3.183, -0.422]}
            rotation={[-0.39, 0, 0]}
            scale={[0.19, 0.665, 0.19]}
          />
          <mesh
            name="mesh_194"
            castShadow
            receiveShadow
            geometry={nodes.mesh_194.geometry}
            material={nodes.mesh_194.material}
            position={[1.096, 3.163, 0]}
            scale={[0.685, 0.125, 0.77]}
          />
        </group>
        <mesh
          name="mesh_195"
          castShadow
          receiveShadow
          geometry={nodes.mesh_195.geometry}
          material={nodes.mesh_195.material}
          position={[-1.317, 3.327, -0.635]}
          rotation={[1.152, 0, 0]}
          scale={[0.299, 0.118, 0.439]}
        />
        <mesh
          name="mesh_196"
          castShadow
          receiveShadow
          geometry={nodes.mesh_196.geometry}
          material={nodes.mesh_196.material}
          position={[-1.431, 3.318, -0.456]}
          rotation={[0.95, 0, 0]}
          scale={[0.299, 0.118, 0.439]}
        />
        <mesh
          name="mesh_197"
          castShadow
          receiveShadow
          geometry={nodes.mesh_197.geometry}
          material={nodes.mesh_197.material}
          position={[-1.852, 2.892, 1.478]}
          scale={[0.217, 0.086, 0.318]}
        />
        <mesh
          name="mesh_198"
          castShadow
          receiveShadow
          geometry={nodes.mesh_198.geometry}
          material={nodes.mesh_198.material}
          position={[-1.809, 2.942, 1.738]}
          rotation={[0.354, 0, 0]}
          scale={[0.217, 0.086, 0.318]}
        />
        <mesh
          name="mesh_199"
          castShadow
          receiveShadow
          geometry={nodes.mesh_199.geometry}
          material={nodes.mesh_199.material}
          position={[-1.538, 0.853, -0.837]}
          rotation={[0, 0.098, 0]}
          scale={[0.54, 0.341, 0.381]}
        />
        <mesh
          name="mesh_200"
          castShadow
          receiveShadow
          geometry={nodes.mesh_200.geometry}
          material={nodes.mesh_200.material}
          position={[-1.538, 0.853, -1.818]}
          rotation={[0, -0.152, 0]}
          scale={[0.54, 0.341, 0.381]}
        />
        <mesh
          name="mesh_201"
          castShadow
          receiveShadow
          geometry={nodes.mesh_201.geometry}
          material={nodes.mesh_201.material}
          position={[-1.536, 0.793, -1.226]}
          rotation={[0, -0.03, 0]}
          scale={[0.36, 0.228, 0.254]}
        />
        <group>
          <mesh
            name="mesh_202"
            castShadow
            receiveShadow
            geometry={nodes.mesh_202.geometry}
            material={nodes.mesh_202.material}
            position={[1.576, 2.028, 0.842]}
            scale={[0.114, 0.101, 0.114]}
          />
          <mesh
            name="mesh_203"
            castShadow
            receiveShadow
            geometry={nodes.mesh_203.geometry}
            material={nodes.mesh_203.material}
            position={[1.576, 1.929, 0.842]}
            scale={[0.036, 0.08, 0.036]}
          />
          <mesh
            name="mesh_204"
            castShadow
            receiveShadow
            geometry={nodes.mesh_204.geometry}
            material={nodes.mesh_204.material}
            position={[1.576, 1.835, 0.842]}
            scale={[0.114, 0.015, 0.114]}
          />
          <mesh
            name="mesh_205"
            castShadow
            receiveShadow
            geometry={nodes.mesh_205.geometry}
            material={nodes.mesh_205.material}
            position={[1.576, 2.028, 0.842]}
            scale={[0.114, 0.101, 0.114]}>
            <group />
          </mesh>
        </group>
        <group>
          <mesh
            name="mesh_206"
            castShadow
            receiveShadow
            geometry={nodes.mesh_206.geometry}
            material={nodes.mesh_206.material}
            position={[-1.389, 3.346, -0.052]}
            rotation={[0, -0.108, 0]}
            scale={[0.124, -0.416, 0.379]}
          />
          <mesh
            name="mesh_207"
            castShadow
            receiveShadow
            geometry={nodes.mesh_207.geometry}
            material={nodes.mesh_207.material}
            position={[-1.408, 3.346, -0.052]}
            rotation={[0, -0.108, 0]}
            scale={[0.142, -0.477, 0.435]}
          />
        </group>
        <group>
          <mesh
            name="mesh_208"
            castShadow
            receiveShadow
            geometry={nodes.mesh_208.geometry}
            material={nodes.mesh_208.material}
            position={[-1.367, 3.346, 0.504]}
            rotation={[0, 0.171, 0]}
            scale={[0.142, -0.477, 0.435]}
          />
          <mesh
            name="mesh_209"
            castShadow
            receiveShadow
            geometry={nodes.mesh_209.geometry}
            material={nodes.mesh_209.material}
            position={[-1.352, 3.346, 0.504]}
            rotation={[0, 0.171, 0]}
            scale={[0.124, -0.416, 0.379]}
          />
        </group>
        <group>
          <mesh
            name="mesh_210"
            castShadow
            receiveShadow
            geometry={nodes.mesh_210.geometry}
            material={nodes.mesh_210.material}
            position={[1.34, 2.112, 0.393]}
            rotation={[0, 0, 0.741]}
            scale={[0.292, 0.026, 0.351]}
          />
          <mesh
            name="mesh_211"
            castShadow
            receiveShadow
            geometry={nodes.mesh_211.geometry}
            material={nodes.mesh_211.material}
            position={[1.366, 2.011, 0.393]}
            scale={[0.292, 0.026, 0.351]}
          />
          <mesh
            name="mesh_212"
            castShadow
            receiveShadow
            geometry={nodes.mesh_212.geometry}
            material={nodes.mesh_212.material}
            position={[1.385, 1.91, 0.393]}
            rotation={[0, 0.053, 0]}
            scale={[0.639, 0.176, 0.639]}
          />
        </group>
        <group>
          <mesh
            name="mesh_213"
            castShadow
            receiveShadow
            geometry={nodes.mesh_213.geometry}
            material={nodes.mesh_213.material}
            position={[1.306, 1.885, 0.864]}
            rotation={[0, -0.067, 0]}
            scale={[0.228, 0.128, 0.18]}
          />
          <mesh
            name="mesh_214"
            castShadow
            receiveShadow
            geometry={nodes.mesh_214.geometry}
            material={nodes.mesh_214.material}
            position={[1.347, 1.979, 0.865]}
            rotation={[0.028, -0.061, 0.432]}
            scale={[0.228, 0.128, 0.108]}
          />
        </group>
        <group />
        <group position={[3.506, -1.163, 0]}>
          <mesh
            name="mesh_215"
            castShadow
            receiveShadow
            geometry={nodes.mesh_215.geometry}
            material={nodes.mesh_215.material}
            position={[-1.678, 3.218, 0.268]}
            rotation={[0, -0.046, 0]}
            scale={[0.142, -0.477, 0.435]}
          />
          <mesh
            name="mesh_216"
            castShadow
            receiveShadow
            geometry={nodes.mesh_216.geometry}
            material={nodes.mesh_216.material}
            position={[-1.663, 3.218, 0.268]}
            rotation={[0, -0.046, 0]}
            scale={[0.124, -0.416, 0.379]}
          />
        </group>
        <group>
          <mesh
            name="mesh_217"
            castShadow
            receiveShadow
            geometry={nodes.mesh_217.geometry}
            material={nodes.mesh_217.material}
            position={[0.73, 4.436, -2.428]}
            scale={[2.35, 0.158, 0.193]}
          />
          <mesh
            name="mesh_218"
            castShadow
            receiveShadow
            geometry={nodes.mesh_218.geometry}
            material={nodes.mesh_218.material}
            position={[0.73, 4.335, -2.424]}
            scale={[2.242, 0.151, 0.142]}
          />
          <mesh
            name="mesh_219"
            castShadow
            receiveShadow
            geometry={nodes.mesh_219.geometry}
            material={nodes.mesh_219.material}
            position={[0.73, 2.286, -2.424]}
            scale={[2.242, 0.151, 0.142]}
          />
          <mesh
            name="mesh_220"
            castShadow
            receiveShadow
            geometry={nodes.mesh_220.geometry}
            material={nodes.mesh_220.material}
            position={[0.73, 2.286, -2.103]}
            scale={[2.242, 0.151, 0.142]}
          />
          <mesh
            name="mesh_221"
            castShadow
            receiveShadow
            geometry={nodes.mesh_221.geometry}
            material={nodes.mesh_221.material}
            position={[0.73, 4.436, -2.103]}
            scale={[2.35, 0.158, 0.193]}
          />
          <mesh
            name="mesh_222"
            castShadow
            receiveShadow
            geometry={nodes.mesh_222.geometry}
            material={nodes.mesh_222.material}
            position={[0.73, 4.335, -2.103]}
            scale={[2.242, 0.151, 0.142]}
          />
        </group>
        <group position={[0.405, 0.204, -1.626]} scale={0.684}>
          <mesh
            name="mesh_223"
            castShadow
            receiveShadow
            geometry={nodes.mesh_223.geometry}
            material={nodes.mesh_223.material}
            position={[0.027, 1.104, 0]}
            scale={[0.6, 0.111, 0.6]}
          />
          <mesh
            name="mesh_224"
            castShadow
            receiveShadow
            geometry={nodes.mesh_224.geometry}
            material={nodes.mesh_224.material}
            position={[-0.423, 0.913, 0]}
            rotation={[0, 0, -0.338]}
            scale={[0.087, 0.173, 0.087]}
          />
          <mesh
            name="mesh_225"
            castShadow
            receiveShadow
            geometry={nodes.mesh_225.geometry}
            material={nodes.mesh_225.material}
            position={[0.477, 0.913, 0]}
            rotation={[0, 0, 0.338]}
            scale={[0.087, 0.173, 0.087]}
          />
          <mesh
            name="mesh_226"
            castShadow
            receiveShadow
            geometry={nodes.mesh_226.geometry}
            material={nodes.mesh_226.material}
            position={[0.027, 0.913, 0.45]}
            rotation={[-0.338, 0, 0]}
            scale={[0.087, 0.173, 0.087]}
          />
          <mesh
            name="mesh_227"
            castShadow
            receiveShadow
            geometry={nodes.mesh_227.geometry}
            material={nodes.mesh_227.material}
            position={[0.027, 0.913, -0.45]}
            rotation={[0.338, 0, 0]}
            scale={[0.087, 0.173, 0.087]}
          />
        </group>
        <group position={[-3.482, -0.14, -2.802]}>
          <mesh
            name="mesh_228"
            castShadow
            receiveShadow
            geometry={nodes.mesh_228.geometry}
            material={nodes.mesh_228.material}
            position={[1.576, 2.028, 0.842]}
            scale={[0.114, 0.101, 0.114]}
          />
          <mesh
            name="mesh_229"
            castShadow
            receiveShadow
            geometry={nodes.mesh_229.geometry}
            material={nodes.mesh_229.material}
            position={[1.576, 1.929, 0.842]}
            scale={[0.036, 0.08, 0.036]}
          />
          <mesh
            name="mesh_230"
            castShadow
            receiveShadow
            geometry={nodes.mesh_230.geometry}
            material={nodes.mesh_230.material}
            position={[1.576, 1.835, 0.842]}
            scale={[0.114, 0.015, 0.114]}
          />
          <mesh
            name="mesh_231"
            castShadow
            receiveShadow
            geometry={nodes.mesh_231.geometry}
            material={nodes.mesh_231.material}
            position={[1.576, 2.028, 0.842]}
            scale={[0.114, 0.101, 0.114]}
          />
        </group>
        <group position={[-3.146, -0.065, 1.132]}>
          <mesh
            name="mesh_232"
            castShadow
            receiveShadow
            geometry={nodes.mesh_232.geometry}
            material={nodes.mesh_232.material}
            position={[1.576, 2.028, 0.842]}
            scale={[0.114, 0.101, 0.114]}
          />
          <mesh
            name="mesh_233"
            castShadow
            receiveShadow
            geometry={nodes.mesh_233.geometry}
            material={nodes.mesh_233.material}
            position={[1.576, 1.929, 0.842]}
            scale={[0.036, 0.08, 0.036]}
          />
          <mesh
            name="mesh_234"
            castShadow
            receiveShadow
            geometry={nodes.mesh_234.geometry}
            material={nodes.mesh_234.material}
            position={[1.576, 1.835, 0.842]}
            scale={[0.114, 0.015, 0.114]}
          />
          <mesh
            name="mesh_235"
            castShadow
            receiveShadow
            geometry={nodes.mesh_235.geometry}
            material={nodes.mesh_235.material}
            position={[1.576, 2.028, 0.842]}
            scale={[0.114, 0.101, 0.114]}
          />
        </group>
        <mesh
          name="mesh_236"
          castShadow
          receiveShadow
          geometry={nodes.mesh_236.geometry}
          material={nodes.mesh_236.material}
          position={[2.059, 1.091, -0.594]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.043, 0.042, 0.042]}
        />
        <group />
        <group />
        <mesh
          name="mesh_237"
          castShadow
          receiveShadow
          geometry={nodes.mesh_237.geometry}
          material={nodes.mesh_237.material}
          position={[-1.644, 3.955, -0.632]}
          rotation={[Math.PI / 2, 1.351, -Math.PI / 2]}
          scale={0.034}
        />
        <group />
        <group />
        <mesh
          name="mesh_238"
          castShadow
          receiveShadow
          geometry={nodes.mesh_238.geometry}
          material={nodes.mesh_238.material}
          position={[-2.086, 4.162, 1.45]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.025}
        />
        <group />
        <mesh
          name="mesh_239"
          castShadow
          receiveShadow
          geometry={nodes.mesh_239.geometry}
          material={nodes.mesh_239.material}
          position={[-2.086, 4.247, 1.45]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.318, 0.334, 0.063]}
        />
        <mesh
          name="mesh_240"
          castShadow
          receiveShadow
          geometry={nodes.mesh_240.geometry}
          material={nodes.mesh_240.material}
          position={[-2.086, 3.887, 1.45]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.318, 0.334, 0.063]}
        />
        <mesh
          name="mesh_241"
          castShadow
          receiveShadow
          geometry={nodes.mesh_241.geometry}
          material={nodes.mesh_241.material}
          position={[-2.086, 3.518, 1.45]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.318, 0.334, 0.063]}
        />
        <mesh
          name="mesh_242"
          castShadow
          receiveShadow
          geometry={nodes.mesh_242.geometry}
          material={nodes.mesh_242.material}
          position={[-2.086, 3.44, 1.45]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.025}
        />
        <mesh
          name="mesh_243"
          castShadow
          receiveShadow
          geometry={nodes.mesh_243.geometry}
          material={nodes.mesh_243.material}
          position={[-2.086, 3.816, 1.45]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.025}
        />
        <mesh
          name="mesh_244"
          castShadow
          receiveShadow
          geometry={nodes.mesh_244.geometry}
          material={nodes.mesh_244.material}
          position={[-2.058, 4.247, 1.45]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.241, 0.287, 0.054]}
        />
        <mesh
          name="mesh_245"
          castShadow
          receiveShadow
          geometry={nodes.mesh_245.geometry}
          material={nodes.mesh_245.material}
          position={[-2.058, 3.897, 1.45]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.241, 0.287, 0.054]}
        />
        <mesh
          name="mesh_246"
          castShadow
          receiveShadow
          geometry={nodes.mesh_246.geometry}
          material={nodes.mesh_246.material}
          position={[-2.058, 3.518, 1.45]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.241, 0.287, 0.054]}
        />
        <group />
        <mesh
          name="mesh_247"
          castShadow
          receiveShadow
          geometry={nodes.mesh_247.geometry}
          material={nodes.mesh_247.material}
          position={[-1.575, 3.017, -0.644]}
          scale={[1.316, 0.176, 3.065]}
        />
        <mesh
          name="mesh_248"
          castShadow
          receiveShadow
          geometry={nodes.mesh_248.geometry}
          material={nodes.mesh_248.material}
          position={[1.513, 1.253, -0.603]}
          scale={[1, 0.888, 3.123]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/p109/other/emsbobashop_FINAL.glb')